base:
  project: housePricePrediction-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/data.csv

load_data:
  raw_dataset_csv: data/raw/data.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2